services:
  interview:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - ./workspace:/workspace
    environment:
      # Configure Node and Python web servers to serve on a public port (to make them available
      # from the Mac host).
      - HOST=0.0.0.0
      # Configure Node web server to access the API server on this port. The default port
      # (5000) is always in use on Macs.
      # https://stackoverflow.com/questions/72369320/why-always-something-is-running-at-port-5000-on-my-mac
      - API_PORT=8111
    ports:
      - "8110:3000"   # React dev server port
      - "8111:8111"   # Python API server port (matches API_PORT above)
    working_dir: /workspace/python-web-interview
